apiVersion: 1

datasources:
  - name: Prometheus
    uid: prometheus
    version: 2
    type: prometheus
    access: proxy
    url: ${PROMETHEUS_URL}
    isDefault: true

  - name: Loki
    uid: loki
    version: 3
    type: loki
    access: proxy
    url: ${LOKI_URL}
    jsonData:
      derivedFields:
        - datasourceUid: tempo
          matcherRegex: '"trace(?:_)?id"\s*:\s*"([A-Fa-f0-9]{32})"'
          name: Trace (json)
          url: "$${__value.raw}"
        - matcherRegex: '"trace(?:_)?id"\s*:\s*"([A-Fa-f0-9]{32})"'
          name: Logs (json)
          url: "/explore?left=%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bservice_name%3D~%5C%22project-starter-api%7Cproject-starter-jobs%5C%22%7D%20%7C~%20%5C%22$${__value.raw}%5C%22%22%7D%5D%7D"
        - datasourceUid: tempo
          matcherRegex: '\\"trace(?:_)?id\\"\s*:\s*\\"([A-Fa-f0-9]{32})\\"'
          name: Trace (escaped)
          url: "$${__value.raw}"
        - matcherRegex: '\\"trace(?:_)?id\\"\s*:\s*\\"([A-Fa-f0-9]{32})\\"'
          name: Logs (escaped)
          url: "/explore?left=%7B%22datasource%22:%22loki%22,%22queries%22:%5B%7B%22refId%22:%22A%22,%22expr%22:%22%7Bservice_name%3D~%5C%22project-starter-api%7Cproject-starter-jobs%5C%22%7D%20%7C~%20%5C%22$${__value.raw}%5C%22%22%7D%5D%7D"

  - name: Tempo
    uid: tempo
    version: 3
    type: tempo
    access: proxy
    url: ${TEMPO_URL}
    jsonData:
      nodeGraph:
        enabled: true
      serviceMap:
        datasourceUid: prometheus
      tracesToMetrics:
        datasourceUid: prometheus
      tracesToLogsV2:
        datasourceUid: loki
        filterByTraceID: true
        filterBySpanID: true
